### ISSUE TITLE
[FEATURE] google.maps.Polygon support

### ISSUE THREAD

**Issue by mortenbo** [huafu/ember-google-map#11]
I'd like polygon support if possible: https://developers.google.com/maps/documentation/javascript/examples/polygon-simple

Thanks!

**Comment by huafu** [comment]
until I'll implement it, you can always use a polyline which path starts and ends with the same point ;-)

**Comment by mortenbo** [comment]
Yeah, true, but I won't be able to style the polygon with a background color etc.

Do you have an estimate on when this feature might be implemented?

**Comment by huafu** [comment]
no estimate sorry, could be tomorrow as in 2 weeks, I am not paid for this so I have to find some free time to do it ;-)

**Comment by mortenbo** [comment]
Totally fine. Thanks :-)

**Comment by huafu** [comment]
@mortenbo here you go! ;-)

**Comment by mortenbo** [comment]
Oh yeah! Thanks :-)
