### ISSUE TITLE
gopt documentation 

### ISSUE THREAD

**Issue by Tuhaj** [huafu/ember-google-map#12]
can you please explain how to use gopt_ on an example?

https://github.com/huafu/ember-google-map/blob/7d5b1cbb709159d05f7873e53493c01248137216/app/components/google-map.js#L54

**Comment by huafu** [comment]
As explained at the end of [this](https://github.com/huafu/ember-google-map#what-is-implemented-for-now) section of the README, you just prepend the google option with `gopt_`. For `backgroundColor` for example:

```handlebars
{{google-map ... gopt_backgroundColor=theBgColor}}
```

**Comment by huafu** [comment]
FYI @Tuhaj I've now created a full documentation available [there](https://github.com/huafu/ember-google-map/wiki). You can find the stuff related to google options in the API section

**Comment by Tuhaj** [comment]
Thanks a lot @huafu

**Comment by Tuhaj** [comment]
Hey @huafu, in my simple app I'm using this:
{{ google-map lat=lat lng=lng type=type zoom=zoom markers=markers gopt_disableDefaultUI=true }}
And I still get the google DefaultUI. Do you know what can be wrong?

**Comment by Tuhaj** [comment]
Nevermind. :-) I reinstalled and It's ok, I had old version of your addon.

**Comment by oswaldoacauan** [comment]
Is this working on Ember 1.13?

Im using Ember 1.13 and the version 0.0.23 and `gopt_disableDefaultUI=true` not seems to work.
