### ISSUE TITLE
ember 2.0 compliant?

### ISSUE THREAD

**Issue by mgenev** [huafu/ember-google-map#14]
Hi,
I spent this weekend trying to make the google map in an ember app and found so many problems with that, I'm seeing that you have done a lot of work solving these problems in your plugin's 'core' folder which is great so I want to try it, but I also see that you are using a lot of controllers and some views which are getting removed in ember 2.0

Do you plan to change this plugin to use only components instead?

**Comment by huafu** [comment]
As answered on gitter directly to you, I am waiting for ember 2.0 decisions are totally made and first version comes up. But yeah I will upgrade this plugin to make it continue working.

--
Huafu Gandon
Head of Tech, Sovolve, LLC
Skype: pedroleouf
www.sovolve.com
Social Evolution, Accelerated 

Try Panomira.  
You'll never look at yourself the same way again.

**Comment by huafu** [comment]
I am closing this issue, will reopen once we have a stable ember 2.0 if the addon is not working anymore
