### ISSUE TITLE
Following example not working

### ISSUE THREAD

**Issue by jmejias** [huafu/ember-google-map#17]
Hi, im trying to follow your docs for the basic example and it doesnt seem to be working

This is my WIP: https://github.com/jmejias/google_maps_example

If you could point out the issue I appreciate it.

Thanks

**Comment by huafu** [comment]
What is the error? Also I see you provided a Google API key, if so, you need to run it on the server with the same origin that the one you defined when creating the API key ;-).

You also set `autoFitBound` but you do not have any data (markers, infoWindows, ...) to show on the map so I don't see the point of setting that ;-)
