### ISSUE TITLE
Error cannot read property 'lat' of undefined

### ISSUE THREAD

**Issue by FutoRicky** [huafu/ember-google-map#18]
Im getting this error and I have lat defined in the controller as well as lng, zoom, and type.

This is the line of code im getting the error on the helper.js line 210

```      return helpers.makeObj(latKey || 'lat', val.lat(), lngKey || 'lng', val.lng()); ```

this are the errors:

```Uncaught TypeError: Cannot read property 'lat' of undefined```
and
``` Uncaught TypeError: Cannot set property 'position' of undefined ```

**Comment by huafu** [comment]
can you gimme the code of your template please whit the line corresponding to where you use the `google-map` component.

**Comment by FutoRicky** [comment]
This is the div where I use the ```google-map``` component:

```
<div id="leftDiv" style="padding-top:30px">


    {{google-map lat=lat lng=lng zoom=zoom type=type }}


</div>

```

**Comment by huafu** [comment]
Hmmm... I might also need to see what/how you defined to the `lat`, `lng`, `zoom` and `type` properties on your controller sorry ;-)

**Comment by FutoRicky** [comment]
```
export default Ember.Controller.extend({

	lat: 0,
	lng: 0,
	zoom: 5,
	type: 'road',
	mapTypes: MAP_TYPES,
});
```

**Comment by huafu** [comment]
Weird, I am going to create a small little ap to check but that should work lol. Also what version of EmberJS and Handlebars are you using?

**Comment by huafu** [comment]
I have just tested with a bare new Ember application, updated to Ember 1.9.1 and Handlebars 2.0.0 (as required by the latest version of my addon), installed my addon, and everything is working :-/

**Comment by FutoRicky** [comment]
Then what might it be? I have ember and handlebars at the required versions.

**Comment by huafu** [comment]
Well the only way I can help you is you share your repository and I can give a try at finding out what it is ;-)

**Comment by FutoRicky** [comment]
@huafu Thanks for your help, I'm still running into the same issue. Here's a link the repo:
https://github.com/FutoRicky/ember-google-maps-sample

**Comment by huafu** [comment]
K, taking a look now

**Comment by huafu** [comment]
Ok, I took a look, I just removed the API key as I don't know what is the hostname you are testing with, and I added a css file: `app/styles/app.css` with this:

```css
.map-canvas {
  width: 400px;
  height: 400px;
}
```

because google map as they say in their documentation you need to specify the dimensions of the map canvas div.

And everything work, I have no error... sorry

**Comment by FutoRicky** [comment]
That was it, the css. Thanks, it's working fine.

**Comment by huafu** [comment]
Hmm, I had no error before I did the CSS too as soon as I saw a 0x0 sized map. Anyway, I need to put that in the readme, there was another issue at the beginning with the same case
