### ISSUE TITLE
ERROR: markerViewClass must be a subclass or an instance of Ember.View, not 

### ISSUE THREAD

**Issue by mattisalokangas** [huafu/ember-google-map#19]
I am running into an issue with the latest version from master.  I've provided the error, my code and versions below.  I have a fork that I just updated from the latest on your master branch.  I'm currently trying to hunt down why this is happening but thought you may get to it sooner.  If I figure it out I'll send you a PR, otherwise hopefully you get this and know what is up.

Let me know what else would be helpful.

**I am getting the following error:**
   
    markerViewClass must be a subclass or an instance of Ember.View, not 

## My Code
    = google-map lat=run.latitude lng=run.longitude zoom=zoom type=type markers=run.markers

## Versions
Ember-CLI                       : 0.1.7
Ember                       : 1.8.1
Ember Data                  : 1.0.0-beta.14.1
Handlebars                  : 1.3.0
jQuery                      : 1.11.2
Ember Simple Auth           : 0.7.2
Ember Simple Auth OAuth 2.0 : 0.7.2
Ember Simple Auth Testing   : 0.7.2

**Comment by mattisalokangas** [comment]
Just saw this is a duplicate.  Sorry about that!

**Comment by huafu** [comment]
The latest version require Ember `>= 1.9`

**Comment by huafu** [comment]
ha, you were faster ;-)
