### ISSUE TITLE
Google Maps API for Work

### ISSUE THREAD

**Issue by davidpaulsson** [huafu/ember-google-map#24]
> Google Maps API for Work developers must not include a key in their requests. Please refer to Loading the Google Maps JavaScript API for instructions.

Therefore `ENV.googleMap = { key: 'AbCDeFgHiJkLmNoPqRsTuVwXyZ' };` won't work.

So how can I use my Google Maps API for Work Client ID using this addon as [specified here](https://developers.google.com/maps/documentation/business/clientside/#client_id)?

**Comment by huafu** [comment]
Will implement this now ;-) Thanks for reporting.

**Comment by huafu** [comment]
Handled in `0.0.18`, remove the `key` and set `clientId` instead.

**Comment by davidpaulsson** [comment]
Awesome!
