### ISSUE TITLE
Does not work without 'unsafe-eval' in your CSP?

### ISSUE THREAD

**Issue by karellm** [huafu/ember-google-map#26]
Is there a way to silent CSP warnings?

`Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' maps.googleapis.com maps.gstatic.com".`

EDIT: I know that adding `unsafe-eval` fixes the issue. The point of my question is not to do it. Thanks!

**Comment by huafu** [comment]
I don't think I am using any `eval`, at least for this addon. But Google might and then you'd have o ask them ;-)

Reopen this issue pointing me to any eval in case I was wrong and forgot I used some.

**Comment by karellm** [comment]
I know it is not your fault, I was simply wondering if you knew a workaround. Thanks!

**Comment by huafu** [comment]
Oh ok ;-) well no I don't know a workaround sorry.
