### ISSUE TITLE
[MISC] Add Content Security Policy

### ISSUE THREAD

**Issue by ohizkiya** [huafu/ember-google-map#31]
We should provide an example of setting the appropriate content security policy in `environment.js` to avoid any warnings in the console so that other developers don't have to track down and resolve the security violations.

**Comment by shennyg** [comment]
The following security policy will stop the warnings:

```javascript
  ENV.contentSecurityPolicy = {
    'default-src': "'none'",
    // Allow scripts
    'script-src': "'self' 'unsafe-eval' http://*.googleapis.com http://maps.gstatic.com",
    'font-src': "'self' http://fonts.gstatic.com", // Allow fonts
    'connect-src': "'self' http://maps.gstatic.com", // Allow data (ajax/websocket)
    'img-src': "'self' http://*.googleapis.com http://maps.gstatic.com http://csi.gstatic.com",
    // Allow inline styles and loaded CSS
    'style-src': "'self' 'unsafe-inline' http://fonts.googleapis.com http://maps.gstatic.com"
  };
````

**Comment by huafu** [comment]
thanks @shennyg I have already the list, but this needs to be done in the doc so that any user can add it itself with their specificities. For example on an https version all URLs would be using `https` protocol instead of `http`, so it'd be better to remove all the protocol in the URLs. But one would like to run this locally or say in cordova for example (not sure that it'd work in the latest) and then the protocol must be specified...

**Comment by huafu** [comment]
@shennyg thanks for updating the FAQ.

@ohizkiya I already "fixed" a bit that [FAQ item](https://github.com/huafu/ember-google-map/wiki/FAQ#4-what-are-those-content-security-policy-errors-in-my-console), can you see if there is a place for it somewhere else in the doc (while keeping it in the FAQ also)?

**Comment by ohizkiya** [comment]
I added a `Configuring your Content Security Policy` section to the configuration page of the wiki -- seemed like the most appropriate place. I think we can close this out.

**Comment by huafu** [comment]
ok cool, thanks a lot. I've added it in the TOC (home page) and replaced the FAQ answer with the link to that page so that we don't have duplicate information that later we'd need to update twice if it needs some fix.
