### ISSUE TITLE
gopt_streetViewControl is not working

### ISSUE THREAD

**Issue by FutoRicky** [huafu/ember-google-map#32]
Should I be doing something else apart from adding the option when I call the map component?

```
{{google-map lat=lat lng=lng zoom=zoom type=type markers=markers gopt_streetViewControl=true}}
```
Do I have to add gopt_streetViewControlOptions?

**Comment by huafu** [comment]
I guess there might be an additional library to load, or maybe some other options. What do they say in google documentation?

**Comment by FutoRicky** [comment]
https://developers.google.com/maps/documentation/javascript/streetview#StreetViewMapUsage

**Comment by huafu** [comment]
I am sorry I still did not get time to look into that yet

**Comment by FutoRicky** [comment]
I made a simple street view component, check it out and see if it helps adding that functionality to your addon. I didn't know how to add it myself. Would be a lot better to have it in the same addon instead of 2 separate ones.
https://github.com/cometaworks/ember-cli-google-street-view

**Comment by huafu** [comment]
Well without adding anything to the options, the street view controls are by default enabled, as you can see on the example [here](http://huafu.github.io/ember-google-map/). I'll upgrade my component so that it's simpler to setup street view options, but by default the street view controls **ARE** there.

**Comment by FutoRicky** [comment]
You're right, and I did know that it was working. But what I was trying to achieve was displaying street view directly without having to actually drop the street view icon on the map.

**Comment by huafu** [comment]
Ah that's something else. Then it needs some option to enable or not the street view mode, and some of the options for the `google.maps.StreetViewPanorama` constructor.

**Comment by huafu** [comment]
@FutoRicky I am closing this issue, will reopen another one more accurate because `gopt_streetViewControl` actually does work.
