### ISSUE TITLE
how to refresh the map?

### ISSUE THREAD

**Issue by Tuhaj** [huafu/ember-google-map#33]
Is there a way provided by ember-google-map?

**Comment by huafu** [comment]
What do you mean by refreshing the map? You should never need to refresh it.

**Comment by Tuhaj** [comment]
So maybe it is a different problem...
In my .hbs i have:

``` {{ google-map lat=lat lng=lng type=type zoom=zoom markers=markers gopt_disableDefaultUI=true }} ```
I changed the lat and lng of the map, and the map stays at the same point. On a change like this I want to move it to a new possition.

**Comment by huafu** [comment]
How you change the `lat` and `lng`? Did you try to follow the example in the [wiki](https://github.com/huafu/ember-google-map/wiki)?

Normally looking at your template you have defined `lat`, `lng`, `type`, `zoom`, `markers` in your controller. To move the map, you in fact want to change `lat` and `lng` property of your controller to the coordinates of the new center. So doing `this.setProperties({lat: <latitude-value>, lng: <longitude-value>});` from your controller will automatically move the map, no need to do anything else.

**Comment by Tuhaj** [comment]
Great! Thanks to you I found the bug :)
