### ISSUE TITLE
Google Styled Maps Support

### ISSUE THREAD

**Issue by gopkumargopi** [huafu/ember-google-map#34]
Does the ember-google-map add-on have support for Google Styled Maps? Google's API that controls the map styles. https://developers.google.com/maps/documentation/javascript/styling

**Comment by huafu** [comment]
I believe (but didn't test) that you can define this style array object in a property of your view (I think it's better to leave this in the view than in the controller), let's say `mapStyles`. Then use this property when calling the component from your template:

```handlebars
{{google-map ... gopt_styles=view.mapStyles}}
```

Lemme know if this does not work (and re-open the issue then).

**Comment by huafu** [comment]
FYI I added a [wiki](https://github.com/huafu/ember-google-map/wiki/Provided-Tools-and-Classes-%28API%29#styling) section for the styling.
