### ISSUE TITLE
Events on marker not working 

### ISSUE THREAD

**Issue by maneeshnanu** [huafu/ember-google-map#37]
I am working on a website developed in Ember-CLI and having Embe Google Map add-on. Ember Google Map add-on is implemented successfully in the app. On clicking the marker the info window shows up with the text, but I would like to perform some other operations as well on click on the marker.
I tried the process explained here: 
"https://github.com/huafu/ember-google-map/wiki/Provided-Tools-and-Classes-%28API%29#example-use-case-responding-to-events"
 and 
"https://github.com/huafu/ember-google-map/wiki/Examples#responding-to-google-events"

Following are the code:

**Template : map/map.hbs**: 
```hbs
{{google-map ...  markerViewClass='map/marker'
  markerInfoWindowTemplateName='map/marker'
  markerController='map/marker'}}
```

**view: map/marker.js**:
```js
export default GoogleMapMarkerView.extend({
  googleEvents: { 
    click: 'markerClick'  /* event tried mouseover and rightclick to get respective events*/
  }
});
```

**controller : map/marker.js (also tried in application.js)**:
```js
export default GoogleMapMarkerController.extend({
  actions: {
    markerClick: function () {
      alert("Clicked here"); 
      return false;
    }
  }
});
```

whenever i try to click the marker I get the following message :
```
Uncaught Error: Nothing handled the action 'markerClick'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.
```

Am i missing anything here or where might be the issue.
Can you please help me out in this issue.

**Comment by huafu** [comment]
Is there a repository on github that I can clone and try to find out what is the issue? Hard to say with just this information ;-)

_sorry to answer that late, have been very busy lately_

**Comment by huafu** [comment]
I'm going to close this. If you have a repo which I can clone or a zip I can download to test and debug that, please reopen providing the link.
