### ISSUE TITLE
use-case: custom lat and lng property names not working

### ISSUE THREAD

**Issue by simo163** [huafu/ember-google-map#42]
Hi all, my model have attributes longitude and latitude (not lat and lng) and I am trying to customize it as explaining in the wiki. But I got this error:

```
Uncaught TypeError: Cannot read property 'lat' of undefined
```
fired in helpers.js line 210
```
return helpers.makeObj(latKey || 'lat', val.lat(), lngKey || 'lng', val.lng());
```

I put some pieces of my code:
```javascript
# template
{{google-map markers=model
                 markerController='map/my-marker'
                 lat=centerLat
                 lng=centerLng
                 zoom=zoom
                 autoFitBounds=true
                 gopt_zoomControl=false
                 type='road'}}

# my-marker controller
import Ember from 'ember';
import GoogleMapMarkerController from '../google-map/marker';

export default GoogleMapMarkerController.extend({
  lat: Ember.computed.alias('coords.latitude'),
  lng: Ember.computed.alias('coords.longitude')
});
```

Do I am doing something wrong?

**Comment by huafu** [comment]
What does your `model` receive as data (the one you give to `markers` in the template)?

**Comment by huafu** [comment]
If I understand well it has `latitude` and `lomgitude`. Markers should be an **array** of objects with latitude and longitude, even if there is only one item in the array.

**Comment by simo163** [comment]
@huafu  thanks for the answer, for now my model returns just an array of hashs which contain latitude and longitude as described in the wiki example but it is not working actually.
```
# route
import Ember from 'ember';
export default Ember.Route.extend({
	model: function() {
		return Ember.A([
	    	{title: "Shop", latitude: 14.766127, longitude: 1.810987},
	      	{title: "Shop1", latitude: 14.762963, longitude: 102.812285}
	   ]);
	}
});

# my-marker
import Ember from 'ember';
import GoogleMapMarkerController from '../google-map/marker';
export default GoogleMapMarkerController.extend({
  lat: Ember.computed.alias('coords.latitude'),
  lng: Ember.computed.alias('coords.longitude')
});
```
Probably coords in the computed property is the reason?
However actually what I want to have later is a call to the web service which will return something like:
´´´
{"shops": [{title: "", latitude: "", longitude: ""}]}
```

**Comment by huafu** [comment]
For the static model, remove `coords`, that is for the example in the doc.

For the data coming from your server, you'll need to plug markers on `shops` and in the extended controller make it alias on `latitude` and `longitude`

**Comment by simo163** [comment]
It seems like what I have done, I really don't know.

**Comment by huafu** [comment]
Please provide either a repo that I can clone to find out what's wrong. What I meant by

> you'll need to plug markers on shops

is in your template:
```hbs
{{google-map ... markers=shops}}
```

and the marker controller:
```js
//...
lat: Ember.computed.alias('latitude'),
lng: Ember.computed.alias('longitude'),
//...
```

That is if your route's `model` hook returns a model like:
```js
{"shops": [{title: "some-title", latitude: 1, longitude: 2}]}
```

**Comment by simo163** [comment]
@huafu Any case seems to work for me,  Thanks for checking the [repo](https://github.com/simo163/ember-cli-google-maps) I am using here just a simple model.

**Comment by huafu** [comment]
Looking at it now, was very busy before sorry!

**Comment by huafu** [comment]
A quick look at it shows me that you forgot to tells the component that you are using a custom marker controller like [there](https://github.com/huafu/ember-google-map/wiki/Provided-Tools-and-Classes-%28API%29#example-use-case-custom-lat-and-lng-property-names): `{{google-map ... markerController='map/marker'}`, also you have to do the same for the `polyline-path` controller so that the array representing the path contains objects with `lat` and `lng` properties.

**Comment by huafu** [comment]
made a PR with some explanation simo163/ember-cli-google-maps#1

**Comment by simo163** [comment]
Many things @huafu for taking some time and looking at it, you're right I was using both markers and polylines such as before I customize the coordinates names. I'll pull your changes and let you know! Thanks again

**Comment by simo163** [comment]
@huafu awesome, it works like a charm, I'll keep looking at the plugin because we're planing to use some complex functionalities with ember and google maps.
