### ISSUE TITLE
[EMBERJS] Object proxying is depreciated

### ISSUE THREAD

**Issue by shennyg** [huafu/ember-google-map#43]
After upgrading ember-cli to 0.2.2 I'm seeing many depreciation notices in my console:

I'm currently running 0.0.19 of ember-google-map, the only difference I see between 0.0.20 is "[Always auto-fit bounds feature](https://github.com/huafu/ember-google-map/commit/21651adf8f38573948dc11fb9d907af39efab5dd)" So I don't think upgrading will fix it.

    DEPRECATION: You attempted to set `lat` from `<app@controller:google-map/marker::ember541>`, but object proxying is deprecated. Please use `model.lat` instead. See http://emberjs.com/guides/deprecations/#toc_objectcontroller for more details.
        at exports.default.mixin.Mixin.create.setUnknownProperty

I'm seeing the depreciation for the following properties:

- lat
- lng
- isWindowVisible
- zIndex
- googleEvents
- isVisible
- isClickable
- icon
- opacity
- title
- isDraggable
- infoWindowTemplateName
- templateName
- hasInfoWindow

I can provide any additional info needed.
Thanks!

**Comment by huafu** [comment]
Thanks for reporting. I saw that they're removing `ObjectController` and I don't know if that would be the case for `ObjectProxy` too.What would be helpful here is if you can find the answer (with references) to these questions (I could look for it but having you doing it would save me some precious time):

- Will `ObjectProxy` be removed too?
- What/how to replace classes extending `ObjectController`?
- Is using `Controller` instead with a `model` property being an instance of `ObjectProxy` a good workaround? (that is if `ObjectProxy is not removed as well)

**Comment by shennyg** [comment]
> - Will `ObjectProxy` be removed too?

I doesn't look like it is happening in v2.0 https://github.com/emberjs/rfcs/pull/45#issuecomment-89650106

I also didn't see any mentions in the [RFCS](https://github.com/emberjs/rfcs/search?utf8=%E2%9C%93&q=objectproxy)

> - What/how to replace classes extending `ObjectController`?

The [depreciation guide](http://emberjs.com/guides/deprecations/#toc_objectcontroller) recommends to use `Controller `, would that have the methods you need?

> - Is using `Controller` instead with a `model` property being an instance of `ObjectProxy` a good workaround? (that is if `ObjectProxy` is not removed as well)

I was unable to get much feedback on IRC or Slack. I did get feedback from @malchak, recommending switching to Components in the So-Cal Ember.js Slack: 

> The only experience I have with this is when you have a list of items and want to perform an action on each individual item, and not the entire list.  Instead of using and itemController (ObjectController), each list element rendered inside of a Component. for example, a &lt;table-row&gt;, or &lt;list-item&gt; component.  Those are the use cases I've seen
-- @malchak

I'm happy to post to http://discuss.emberjs.com/ if you need more input.

Thank you @huafu

**Comment by btecu** [comment]
**Deprecate**... Depreciate is a decrease in value.

**Comment by huafu** [comment]
Yeah, I did not even saw that mistake. But it's ok we all understood ;-) I guess @shennyg is like me and English is not his first language.

**Comment by tommyblue** [comment]
Hi @huafu, any news on this?
I get thousands deprecation warning using polylines. I'm now using ember-cli 0.2.5
This is not a big problem now, but the ember roadmap after some warnings, fully deprecate some old features, so in the future everything will probably stop working :/

**Comment by huafu** [comment]
I know, but I am being so busy right now that I cannot do the refactor. It is definitely planned, and don't worry, the project will **NOT** be abandoned, I need this addon too hehe. But yeah, I can't do that now, sorry!
