### ISSUE TITLE
Reverse geocoding - listen to events on the actual Map (google.maps.Map)

### ISSUE THREAD

**Issue by vasilakisfil** [huafu/ember-google-map#44]
I am trying to achieve reverse geocoding with this amazing ember addon. All I want is when the user clicks on the map to propagate the coordinates using an action.

However I am not sure how I can achieve that. I tried:

```hbs
{{google-map
  lat=40
  lng=-74
  zoom=8
  gopt_zoomControl=false
  type='map'
  coreViewClass='map/reverse-geocoding'
}}
```

And inside the view I have tried all events but nothing worked ^_^:

```javascript
import Ember from 'ember';
import GoogleMapCoreView from '../google-map/core';

export default GoogleMapCoreView.extend({
  googleEvents: {
    click: 'didclick'
  },

  click: function() {
    alert('hey!');
  },
});
```

I defined a `didClick` action on ApplicationRoute but it got nothing.

How would you do that ? I think it's a good case to have it on ReadMe too :)

**Comment by huafu** [comment]
```js
import GoogleMapCoreView from '../google-map/core';
```
I don't think there is such a view ;-)

Anyway @vasilakisfil I think this is not documented in the doc. I believe the easiest for now would be to set the `googleEvents` property of the component with one defined in your controller:

```js
// app/controllers/my-map.js
// [...]
  googleMapEvents: {click: 'didClick'},
  // [...]
  actions: {
    didClick: function() {
      // handle the click here, check the arguments with debug I do not remember their order but there should be the sender ember object as well as the event object itself
    }
// [...]
```

```hbs
{{! app/templates/my-map.hbs }}
{{google-map ... googleEvents=googleMapEvents}}
```

**Comment by huafu** [comment]
@vasilakisfil I dunno if you still worry about this, but you can now listen to events on the component directly with `ev_click='actionName'` and that action of your controller will be called with second argument being the event, having `latLng` property being the `google.map.LatLng` object where the click happened.

https://github.com/huafu/ember-google-map/wiki/Provided-Tools-and-Classes-(API)#send-action-on-google-event
