### ISSUE TITLE
[Question] Unable to access Google map object

### ISSUE THREAD

**Issue by zulaica** [huafu/ember-google-map#45]
I'm attempting to be able to redraw the center of the map based on geolocation. Adding `map=view.googleMap` to the component does not provide `googleMap` (console is telling me it's undefined). Everything else appears to be loading properly, I'm just looking to be able to access `googleMap.setCenter(latlng)`. 

Is there something I'm missing? Or, I suppose more importantly, is this currently possible? Thanks!

**Comment by huafu** [comment]
Center is bound to `lat` and `lng` properties of the component, so if in your template you have `{{google-map lat=lat lng=lng}}` and in your controller you do `this.setProperties({lat: <new-lat>, lng: <new-lng>})` it'll automatically change the center of the map. That is the first purpose of this component, 2 way bindings between Google Map (and anything drawn on it) and Ember objects, so no need to access the core map object.
