### ISSUE TITLE
autoFitBounds not resizing and scrolling to marker position when setting markers dynamically

### ISSUE THREAD

**Issue by blisst** [huafu/ember-google-map#46]
Hello, 
I am setting a marker on the map dynamically via a location search bar.

The search bar gets latitude and longitude info and then sets a controller property:
```
// lat and lng provided by a search bar
controller.set('markers',Ember.A([{
	lat: lat,
	lng: lng,
}]));
```

I'm using the component as so:

```
{{google-map autoFitBounds=true markers=markers}}
```

I have checked that the `google-map` component is updating the markers correctly using the console using the view number of the component, (the ember-google-map is ember518 in my case):
```
Ember.View.views['ember518'].get('markers')  //returns correct values
```
It also displays the marker on the map correctly.

However, it does not automatically scroll and resize the map to fit the marker. 

Am I missing something?

**Comment by huafu** [comment]
Yes, you are missing the `alwaysAutoFitBounds=true`, by default it fit bounds on load only ;-)
