### ISSUE TITLE
Deprecation warning with latest Ember 1.12.1

### ISSUE THREAD

**Issue by ignacykasperowicz** [huafu/ember-google-map#56]
1. With latest Ember 1.12.1 I get deprecation warning related to changes with computed properties:
http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter
in `fitBoundsArray` computed property:
https://github.com/huafu/ember-google-map/blob/master/app/components/google-map.js#L161

2. With the same 1.12.1 I get:
`Ember.required is deprecated as its behavior is inconsistent and unreliable` in here: https://github.com/huafu/ember-google-map/blob/master/addon/mixins/google-object.js#L62

Would be nice to have this fixed :)

**Comment by huafu** [comment]
Let's keep track of this in #67 ;-)
