### ISSUE TITLE
How to update polygon properties

### ISSUE THREAD

**Issue by kevintraver** [huafu/ember-google-map#57]
For example, on a click event, change the fillColor to blue.

I tried this, but it does not work.

```
didClick: function(event){
  event.set('controller.model.fillColor','blue');
}
```

**Comment by huafu** [comment]
This is yet not supported without re-initializing the polygone. I'll work on supporting this in a future version.

BTW, if the event is triggered by Google Maps itself thru this addon, the event handler should receive another parameter which is the model to be accessed directly

**Comment by kevintraver** [comment]
Awesome! Thanks for the update.

**Comment by kevintraver** [comment]
Closing out (inactivity)
