### ISSUE TITLE
Blank map?

### ISSUE THREAD

**Issue by brandonparsons** [huafu/ember-google-map#62]
I'm not quite sure what I'm doing wrong - help would be appreciated.

I've tried including the base component in my application:

```javascript
{{google-map lat=0 lng=0}}
```

And all I get is a blank/empty div I've tried setting other `lat` and `lng` values but to no avail.

Everything is installed properly - I get the following when booting the ember app:

`DEBUG: [google-maps] creating new map: {zoom: 5, mapTypeId: roadmap, center: (0, 0)}`

The DOM elements appear to be there, but I can't see anything!

**Comment by huafu** [comment]
You need to define a with and height to the canvas div, look at the docs in the wiki of this repo (can't link to the right page now, on my phone)

**Comment by brandonparsons** [comment]
:+1: Thanks.

Sorry - I thought I had done this (I did read through the wiki). But it turns out I got myself confused between a few files...... :)
