### ISSUE TITLE
gopt not working

### ISSUE THREAD

**Issue by cbeckfield** [huafu/ember-google-map#64]
Hey, having an issue with Google options. Made a map a while back that worked 100% correctly, but I just noticed that it is now not taking gopt options when it used to. The map still works fine but none of the options are applying (no scroll wheel, no UI, etc.etc.). I've tried going back to previous versions of the addon but that didn't seem to help. I am using the Ember 1.13 beta, could that be causing it?

**Comment by huafu** [comment]
Yup, `1.13` support is almost there in a branch, not all issues fixed but so far getting close to a release supporting it ;-)

**Comment by huafu** [comment]
Closing in favor of #67
