### ISSUE TITLE
Sending event using ev_[eventName] not working

### ISSUE THREAD

**Issue by thagul** [huafu/ember-google-map#68]
I've defined the event `ev_bounds_changed="search"` and using ember 1.13.1 it doesn't fire action `search` in my controller.

I've defined `google-map` in this way:

    {{google-map lat=centerLat lng=centerLng zoom=14 ev_bounds_changed="search"}}

**Comment by blisst** [comment]
Any resolution to this?

**Comment by huafu** [comment]
The support for 1.13 is not yet fully ready. Will be soon but still some little bugs to fix. See #67 ;-)
