### ISSUE TITLE
is not a function on markers change

### ISSUE THREAD

**Issue by MichalBryxi** [huafu/ember-google-map#80]
I have markers in my google-map:

```
{{google-map
    markers=markers}}
```

and I'm recalculating them once in a while. Namely changin icon URL under some conditions:

```
  markers: function () {
    var currentId = this.get('controllers.section.attrs.section.id');
    console.log('recalculating markers for: ', currentId);

    return this.get('attrs.sections').map(function (item) {
      var icon = null;
      if (item.get('id') === currentId) {
        icon = '//maps.google.com/mapfiles/ms/icons/blue-dot.png';
      } else {
        icon = '//maps.google.com/mapfiles/ms/icons/red-dot.png';
      }
      return {title: item.get('title'), lat: item.get('lat'), lng: item.get('long'), icon: icon};
    });
  }.property('attrs.sections.[]', 'controllers.section.attrs.section.id'),
```

And in some cases I get following uncaught error:
```
google-object-property.js:94 Uncaught TypeError: googleObject[("get" + capitalize(...))] is not a function
```

Which leads to [this line of code](https://github.com/huafu/ember-google-map/blob/7c1e8283e7307ab4cfdb465d134c8ef637b85e20/addon/core/google-object-property.js#L97).

Anybody has clue what is wrong here?

**Comment by MichalBryxi** [comment]
Just tested that it's problem with Ember `1.13.x`.

**Comment by huafu** [comment]
@MichalBryxi you should make each marker an ember object and change it in that case instead of changing the whole array of markers each time. Anyway, that sounds like a minor bug that will be addressed by the rework for v1
