### ISSUE TITLE
Fix suggestion for index.js (making sure map api JS loaded from http://)

### ISSUE THREAD

**Issue by rakabali78** [huafu/ember-google-map#88]
Hi,

In index.js, please change this line:

src = "//maps.googleapis.com/maps/api/js";

to...

src = "http://maps.googleapis.com/maps/api/js";

This ensures that this plugin will work on ember-app packaged as Cordova application.
Otherwise you'll be getting this error: GET file://maps.googleapis.com/maps/api/js net::ERR_FILE_NOT_FOUND (you see, it's using the file:// scheme in absence of http://)

I did it and it works now in my cordova-packaged ember-app.

Thanks,
Raka

**Comment by huafu** [comment]
You can change that URL in the settings (`environment.js`). The `//` here
is to use the same protocol as the webpage, so `http` if not secure and
`https` for secure ones. Since cordova is a special case, you should change
it in the settings as explained in the wiki.

**Comment by gnazarkin** [comment]
Came across this as well and have been trying to overwrite in on config. What property is it supposed to pick up on/if any? Looked at the index.html file and it seems it doesn't grab it from config.

Thanks

**Comment by huafu** [comment]
Added in 0.0.24 which is on its way. I added a `protocol` option to be set in the `googleMap` config section of your environment, like the other options. If not set, it'll act as before, else you can specify `http` or `https` and it'll add it with `:` in front of the URL
