### ISSUE TITLE
autoFitBounds broken on 0.0.22 and 0.0.23

### ISSUE THREAD

**Issue by yinquanteo** [huafu/ember-google-map#90]
For v0.0.22 and v0.0.23, setting `autoFitBounds=true` on the google-map object doesn't automatically center and zoom the map so that all of the objects are visible. This works for v0.0.21. 

I believe this is fixed by 981d345b3b1acf7f01a335e48509c92cd9e75368

Could we release 0.0.24 with this fix?

**Comment by huafu** [comment]
Fixed in 0.0.24 which is on its way
